admins/urls.py
from django.urls import path
from .views import (
  adminsLogin_view,
  adminsHome_view,
  adminsManageJob_view,
  adminsManageEmployee_view,
  adminsManageEmployer_view
)

app_name = 'admins'

urlpatterns = [
  path('login/', adminsLogin_view, name='adminsLogin_view'),
  path('home/', adminsHome_view, name='adminsHome_view'),
  path('manage-jobs/', adminsManageJob_view, name='adminsManageJob_view'),
  path('manage-employees/', adminsManageEmployee_view, name='adminsManageEmployee_view'),
  path('manage-employers/', adminsManageEmployer_view, name='adminsManageEmployer_view'),
]

eJobPortal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name="home-view"),
    path('logout/', logoutUser, name="logoutUser"),
    path('employee/', include('employee.urls', namespace='employee')),
    path('employer/', include('employer.urls', namespace='employer')),
    path('admins/', include('admins.urls', namespace='admins')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

employee/urls.py
from django.urls import path
from .views import (
  employeeLogin_view,
  employeeSignUp_view,
  employeeHome_view,
  employeeProfile_view,
  employeeTrackApplication_view,
  employeeListThreads_view,
  employeeThreadView,
  employeeCreateMessageView
)

app_name = 'employee'

urlpatterns = [
  path('login/', employeeLogin_view, name='employeeLogin_view'),
  path('signup/', employeeSignUp_view, name='employeeSignUp_view'),
  path('home/', employeeHome_view, name='employeeHome_view'),
  path('profile/', employeeProfile_view, name='employeeProfile_view'),
  path('track-applications/', employeeTrackApplication_view, name='employeeTrackApplication_view'),
  path('inbox/', employeeListThreads_view, name='employeeListThreads_view'),
  path('inbox/<int:pk>/', employeeThreadView, name='employeeThreadView'),
  path('inbox/<int:pk>/create-message/', employeeCreateMessageView, name='employeeCreateMessageView'),
]

employee/models.py
from django.db import models
import jsonfield
from user.models import User
from django.contrib.auth.models import BaseUserManager
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.core.validators import FileExtensionValidator
from employer.models import Job

class EmployeeManager(BaseUserManager):
  def get_queryset(self, *args, **kwargs):
    results = super().get_queryset(*args, **kwargs)
    return results.filter(role=User.Role.EMPLOYEE)

class EmployeeRole(User):
  base_role = User.Role.EMPLOYEE
  employee = EmployeeManager()
  class Meta:
    proxy = True

@receiver(post_save, sender=EmployeeRole)
def create_user_profile(sender, instance, created, **kwargs):
  if created and instance.role == "EMPLOYEE":
    Employee.objects.create(user=instance)

availabilityType = [
  ('Ready to interview', 'Ready to interview'),
  ('Open to offers', 'Open to offers'),
  ('Closed to offers', 'Closed to offers')
]

class Employee(models.Model):
  id = models.BigAutoField(primary_key=True)
  photo = models.ImageField(default='avatar.png', upload_to='', blank=True)
  location = models.CharField(max_length=200, blank=True)
  achievement = jsonfield.JSONField(blank=True, null=True)
  phone_no = models.CharField(max_length=15, blank=True)
  primary_role = models.CharField(max_length=50, blank=True)
  user = models.OneToOneField(User, on_delete=models.CASCADE)
  experience = models.IntegerField(blank=True, null=True, default = 0)
  secondary_role = models.CharField(max_length=150, blank=True)
  bio = models.CharField(max_length=250, blank=True)
  resume = models.FileField(upload_to='', blank=True, default = None, validators=[FileExtensionValidator(allowed_extensions=["pdf"])])
  social_profiles = jsonfield.JSONField(blank=True, null=True)
  work_experience = jsonfield.JSONField(blank=True, null=True)
  education = jsonfield.JSONField(blank=True, null=True)
  skills = models.CharField(max_length=350, blank=True)
  availability = models.CharField(max_length=50, blank=True, choices=availabilityType)

class JobApplications(models.Model):
  id = models.BigAutoField(primary_key=True)
  employee_id = models.ForeignKey(Employee, to_field='id', on_delete=models.CASCADE)
  job_id = models.ForeignKey(Job, to_field='id', on_delete=models.CASCADE)
  status = models.CharField(max_length=50, default="pending", null=False, blank=False)

employee/forms.py
from django import forms
from .models import Employee

class EmployeeModelForm(forms.ModelForm):
  class Meta:
    model = Employee
    fields = (
      'location',
      'achievement',
      'phone_no',
      'photo',
      'primary_role',
      'experience',
      'secondary_role',
      'bio',
      'resume',
      'social_profiles',
      'work_experience',
      'education',
      'skills',
      'availability',
    )

class MessageForm(forms.Form):
  message = forms.CharField(label='', max_length=3000)

employee/views.py
from django.shortcuts import render, redirect
from .models import EmployeeRole, Employee, JobApplications
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
from django.contrib import messages
from .forms import EmployeeModelForm, MessageForm
from employer.models import Job
from itertools import chain
from user.models import ThreadModel, Messages, User
from django.db.models import Q
from django.shortcuts import redirect

def employeeLogin_view(request):
  if request.user.is_authenticated:
    return render(request, 'home.html')
  if request.method == 'POST':
    name = request.POST.get('name')
    password = request.POST.get('pass')
    user = authenticate(username=name, password=password)

    if user is not None and user.role == 'EMPLOYEE':
      login(request, user)
      return redirect('employee:employeeHome_view')
    else:
      messages.error(request,'Email or password is incorrect.')
      return redirect('employee:employeeLogin_view')
  return render(request, 'login.html')

def employeeSignUp_view(request):
  if request.user.is_authenticated:
    return render(request, 'home.html')
  if request.method == 'POST':
    ename = request.POST.get('name')
    email = request.POST.get('email')
    password = request.POST.get('pass')
    emp = EmployeeRole.objects.create_user(username=ename, email=email, password=password)
    return redirect('employee:employeeLogin_view')
  return render(request, 'signup.html')

@login_required
def employeeHome_view(request):
  if request.user.role == 'EMPLOYEE':
    jobs = Job.objects.all()
    employee = Employee.objects.filter(user=request.user).first()
    confirm = False
    confirmError = ''
    form_data = {}
    if request.method == 'POST':
      form_data = request.POST.dict()
      if len(form_data) > 1 and 'title' in form_data :
        d1 = Job.objects.all()
        if (form_data['title']):
          d1 = d1.filter(title__icontains=form_data['title'])
        if (form_data['company']):
          d1 = d1.filter(company_name__icontains=form_data['company'])
        if form_data['experience']:
          d1 = d1.filter(experience=form_data['experience'])
        if (form_data['package']):
          d1 = d1.filter(package__icontains=form_data['package'])
        if form_data['location']:
          d1 = d1.filter(location__icontains=form_data['location'])
        jobs = d1
      else:
        if form_data['submit']:
          try:
            instance = JobApplications(employee_id_id = employee.id, job_id_id = form_data['submit'], status = 'pending')
            instance.save()
            confirm = True
            confirmError = ''
          except Exception as e:
            confirmError = e
    
    appliedJobsObj = JobApplications.objects.filter(employee_id=employee.id)
    appliedJobs = list(appliedJobsObj.values_list('job_id', flat=True))

    context = {
      'jobs': jobs,
      'appliedJobs': appliedJobs,
      'confirm': confirm,
      'confirmError': confirmError,
      'formData': form_data
    }
    return render(request, 'home.html', context)

@login_required
def employeeProfile_view(request):
  if request.user.role == 'EMPLOYEE':
    employee = Employee.objects.filter(user=request.user).first()
    form = EmployeeModelForm(request.POST or None, request.FILES or None, instance=employee)
    confirm = False
    confirmError = ''

    if request.method == 'POST':
      form_data = request.POST.dict()
      if (len(form_data) > 0):
        socialProfileObj = {
          'website': form_data['website'],
          'github': form_data['github'],
          'linkedIn': form_data['linkedIn'],
          'twitter': form_data['twitter']
        }
        workObj = []
        educationObj = []
        achievementObj = []
        for m in form_data:
          if m.startswith('achievement') and len(form_data[m]) > 0:
            achievementObj.append({m: form_data[m]})
          if m.startswith('wrk') and len(form_data[m]) > 0:
            prefix, suffix, number = m.split("-")
            if (len(workObj) <= (int(number))):
              while (len(workObj) <= (int(number))):
                workObj.append({})
            workObj[int(number)][m] = form_data[m]
          if m.startswith('ed') and len(form_data[m]) > 0:
            prefix2, suffix2, number2 = m.split("-")
            if (len(educationObj) <= (int(number2))):
              while (len(educationObj) <= (int(number2))):
                educationObj.append({})
            educationObj[int(number2)][m] = form_data[m]
        try:
          employee.location = form_data['location']
          employee.achievement = achievementObj
          employee.phone_no = form_data['phone_no']
          employee.primary_role = form_data['primary_role']
          employee.experience = form_data['experience']
          employee.secondary_role = form_data['secondary_role']
          employee.bio = form_data['bio']
          employee.social_profiles = socialProfileObj
          employee.work_experience = workObj
          employee.education = educationObj
          employee.skills = form_data['skills']
          employee.availability = form_data['availability']
          if request.FILES.get('resume'):
            employee.resume = request.FILES.get('resume')
          if request.FILES.get('photo'):
            employee.photo = request.FILES.get('photo')
          employee.save()
          confirm = True
          confirmError = ''
        except Exception as e:
          confirmError = e
    
    context = {
      'employee': employee,
      'confirm': confirm,
      'confirmError': confirmError
    }
    return render(request, 'profile.html', context)

@login_required
def employeeTrackApplication_view(request):
  if request.user.role == 'EMPLOYEE':
    emp = Employee.objects.filter(user=request.user).first()
    confirm = False
    confirmError = ''

    if request.method == 'POST':
      form_data = request.POST.dict()
      if form_data['submit']:
        try:
          JobApplications.objects.filter(employee_id=emp.id, job_id=form_data['submit']).delete()
          confirm = True
          confirmError = ''
        except Exception as e:
          confirmError = e

    appliedJobsObj = JobApplications.objects.filter(employee_id=emp.id)
    ids = list(appliedJobsObj.values_list('job_id', flat=True))
    status = list(appliedJobsObj.values_list('status', flat=True))
    jobs = []
    for i in ids:
      job = Job.objects.filter(id=i).first()
      jobs.append(job)

    job_status = zip(jobs, status)

    context = {
      'jobs': job_status,
      'confirm': confirm,
      'confirmError': confirmError
    }

    return render(request, 'track-application.html', context)

@login_required
def employeeListThreads_view(request):
  if request.user.role == 'EMPLOYEE':
    threads = ThreadModel.objects.filter(Q(user=request.user) | Q(receiver=request.user))
    context = {
      'threads': threads
    }
    return render(request, 'inbox.html', context)

@login_required
def employeeThreadView(request, pk):
  if request.user.role == 'EMPLOYEE':
    form = MessageForm()
    thread = ThreadModel.objects.get(pk=pk)
    messageList = Messages.objects.filter(thread__pk__contains=pk)
    context = {
      'thread': thread,
      'form': form,
      'messageList': messageList
    }
    return render(request, 'social-thread.html', context)

@login_required
def employeeCreateMessageView(request, pk):
  if request.user.role == 'EMPLOYEE':
    thread = ThreadModel.objects.get(pk=pk)
    if thread.receiver == request.user:
      receiver = thread.user
    else:
      receiver = thread.receiver

    message = Messages(
      thread=thread,
      from_id=request.user,
      to_id=receiver,
      description=request.POST.get('message')
    )
    message.save()
    return redirect('employee:employeeThreadView', pk=pk)

employee/templates/home.html
{% extends "base.html" %}

{% block content %}
<div class="page">
  <div class="page-box">
    <h3>Filters:</h3>
    <div>
      <form action="" method="POST" id="empFilterForm" class="ui form empFilter" enctype='multipart/form-data'>
        {% csrf_token %}
        <label for="title">Title:</label>
        <input type="text" placeholder="Eg - SDE" name="title" id="title" value="{{formData.title}}">
        <label for="company">Company:</label>
        <input type="text" placeholder="Eg - GIVA" name="company" id="company" value="{{formData.company}}">
        <label for="name">Experience:</label>
        <input type="number" placeholder="Eg - 3" name="experience" id="experience" value="{{formData.experience}}">
        <label for="name">Package:</label>
        <input type="text" placeholder="Eg- 4LPA" name="package" id="package" value="{{formData.package}}">
        <label for="name">Location:</label>
        <input type="text" placeholder="Eg- Delhi" name="location" id="location" value="{{formData.location}}">
        <div class="actions">
          <button type='submit' class="btn btn-light">Apply</button>
        </div>
      </form>
    </div>
    {% if confirm %}
      <div class="ui green message">Job applied successfully!!!</div>
    {% elif confirmError != '' %}
      <div class="ui red message">{{confirmError}}</div>
    {% endif %}
    {% if jobs|length == 0 %}
      No jobs available.
    {% endif %}
    {% for j in jobs %}
      {% if j.status == 'approved' %}
        <div class="ui modal mymodal mymodal{{forloop.counter0}}">
          <button style="float: right; margin: 10px;" onclick="hideEmp('mymodal{{forloop.counter0}}')"><i class="close icon" id="close-modal-btn"></i></button>
          <div class="header"></div>
          <div class="image content">
            <div class="ui medium image">
              <div class="prof-img">
                {% if j.logo %}
                  <img class="ui medium rounded image" src={{j.logo.url}}>
                {% else %}
                  <img class="ui medium rounded image" src="/media/empty-img.png">
                {% endif %}
              </div>
            </div>
            <div class="description">
              <table class="table table-striped table-dark">
                <tbody>
                  {% if j.title %}
                    <tr>
                      <td>Title</td>
                      <td>{{j.title}}</td>
                    </tr>
                  {% endif %}
                  {% if j.company_name %}
                    <tr>
                      <td>Company Name</td>
                      <td>{{j.company_name}}</td>
                    </tr>
                  {% endif %}
                  {% if j.location %}
                    <tr>
                      <td>Location</td>
                      <td>{{j.location}}</td>
                    </tr>
                  {% endif %}
                  {% if j.about %}
                    <tr>
                      <td>About</td>
                      <td>{{j.about}}</td>
                    </tr>
                  {% endif %}
                  {% if j.qualifications %}
                    <tr>
                      <td>Qualifications</td>
                      <td>{{j.qualifications}}</td>
                    </tr>
                  {% endif %}
                  {% if j.responsibility %}
                    <tr>
                      <td>Responsibility</td>
                      <td>{{j.responsibility}}</td>
                    </tr>
                  {% endif %}
                  {% if j.experience %}
                    <tr>
                      <td>Experience</td>
                      <td>{{j.experience}}</td>
                    </tr>
                  {% endif %}
                  {% if j.job_type %}
                    <tr>
                      <td>Job Type</td>
                      <td>{{j.job_type}}</td>
                    </tr>
                  {% endif %}
                  {% if j.package %}
                    <tr>
                      <td>Package</td>
                      <td>{{j.package}}</td>
                    </tr>
                  {% endif %}
                  {% if j.skills %}
                    <tr>
                      <td>Skills</td>
                      <td>{{j.skills}}</td>
                    </tr>
                  {% endif %}
                </tbody>
              </table>
              <a href="{% url 'employee:employeeProfile_view' %}"><p style="margin-bottom: 10px;">Want to update profile first? Click here.</p></a>
              <form action="" method="POST" style="display: flex; gap: 20px;">
                {% csrf_token %}
                <button class="empcard-btn btn btn-success" type="submit" value="{{j.id}}" name="submit">Apply Now</button>
              </form>
            </div>
          </div>
        </div>
        <div class="empcard ">
          <div class="empcard-description">
            <h2 class="empcard-description-title">{{j.title}}</h2>
            <span class="empcard-description-subtitle">{{j.company_name}}</span>
            <span class="empcard-description-subtitle">{{j.location}}</span>
            <div class="empcard-btn-box">
              {% if j.id in appliedJobs %}
                <button class="empcard-btn btn btn-success disabled">Applied already</button>
              {% else %}
                <button class="empcard-btn btn btn-info" onclick="viewEmp('mymodal{{forloop.counter0}}')">View and Apply</button>
              {% endif %}
            </div>
          </div>
          <div class="emp-card-img">
            {% if j.logo %}
              <img class="empcard-image" src={{j.logo.url}}>
            {% else %}
              <img class="empcard-image" src="/media/empty-img.png">
            {% endif %}
          </div>
        </div>
      {% endif %}
    {% endfor %}
  </div>
</div>
{% endblock %}

employee/templates/inbox.html
{% extends "base.html" %}

{% block content %}
<div class="page">
  <div class="page-box">
    <div style="padding: 3rem 0 0 3rem!important;">
      <h2>Your Conversations -</h2>
    </div>
    {% for thread in threads.all %}
      <div class="row mb-3 p-5" style="border-bottom: 2px solid white;">
        <div class="card text-white bg-secondary mb-3 col-md-12 p-3 shadow-sm">
          <h5>{{ thread.user }} - {{ thread.receiver }}</h5>
          <a class="stretched-link" href="{% url 'employee:employeeThreadView' thread.pk %}"></a>
        </div>
      </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

employee/templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="form-bg">
  <form class="ui form form-box" method="post">
    {% csrf_token %}
    <h2>Sign In</h2>
    <hr>
    <div class="field">
      <label>Username</label>
      <input type="text" name="name" placeholder="Eg - Akshita">
    </div>
    <div class="field">
      <label>Password</label>
      <input type="password" name="pass" placeholder="Eg - *********">
    </div>
    <button type="submit" class="btn btn-light">Sign In</button>
    <a href="{% url 'employee:employeeSignUp_view' %}" >Not registered? Sign-up here</a>
    {% for message in messages %}
      <div class="alert alert-danger">
        <a class="close" href="#" data-dismiss="alert">×</a>
        {{ message }}
      </div>
    {% endfor %}
  </form>
</div>
{% endblock %}

employee/templates/signup.html
{% extends "base.html" %}

{% block content %}
<div class="form-bg">
  <form method="post" class="ui form form-box">
    {% csrf_token %}
    <h2>Sign Up</h2>
    <hr>
    <div class="field">
      <label>Name</label>
      <input type="text" placeholder="Eg - Akshita Jain" name="name">
    </div>
    <div class="field">
      <label>E-mail</label>
      <input type="email" placeholder="Eg - akshita@gmail.com" name="email">
    </div>
    <div class="field">
      <label>Password</label>
      <input type="password" placeholder="Eg - *********" name="pass">
    </div>
    <button type="submit" class="btn btn-light">Get Started</button>
    <a href="{% url 'employee:employeeLogin_view' %}" >Already have an account? Sign-in here.</a>
  </form>
</div>
{% endblock %}

employee/templates/social-thread.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="page">
  <div class="page-box">
    <div class="container">
      <div class="row">
        <div class="card text-white bg-secondary mb-3 col-md-12 mt-5 p-3 shadow-sm">
          {% if thread.receiver == request.user %}
            <h5>@{{ thread.user }}</h5>
          {% else %}
            <h5>@{{ thread.receiver }}</h5>
          {% endif %}
        </div>
      </div>
      {% if messageList.all.count == 0 %}
      <div class="row my-5">
        <div class="col-md-12">
          <p class="empty-text">No Messages</p>
        </div>
      </div>
      {% endif %}
    
      {% for message in messageList %}
      <div class="row">
        <div class="col-md-12 my-1">
          {% if message.from_id == request.user %}
            <div class="sent-message my-3">
              <p>{{ message.description }}</p>
            </div>
          {% elif message.to_id == request.user %}
            <div class="received-message my-3">
              <p>{{ message.description }}</p>
            </div>
          {% endif %}
        </div>
      </div>
      {% endfor %}
    
      <div class="row">
        <div class="card text-white bg-secondary mb-3 col-md-12 p-3 shadow-sm">
          <form method="POST" action="{% url 'employee:employeeCreateMessageView' thread.pk %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form | crispy }}
            <div style="display: flex;">
              <button class="btn btn-info center" type="submit">Send Message</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

employee/templates/track-application.html
{% extends "base.html" %}

{% block content %}
<div class="page">
  <div class="page-box">
    {% if confirm %}
      <div class="ui green message">Your application has been withdrawn successfully.</div>
    {% elif confirmError != '' %}
      <div class="ui red message">{{confirmError}}</div>
    {% endif %}
    {% for j, s in jobs %}
      <div class="ui modal mymodal mymodal{{forloop.counter0}}">
        <button style="float: right; margin: 10px;" onclick="hideEmp('mymodal{{forloop.counter0}}')"><i class="close icon" id="close-modal-btn"></i></button>
        <div class="header"></div>
        <div class="image content">
        <div class="ui medium image">
          <div class="prof-img">
            {% if j.logo %}
              <img class="ui medium rounded image" src={{j.logo.url}}>
            {% else %}
              <img class="ui medium rounded image" src="/media/empty-img.png">
            {% endif %}
          </div>
        </div>
        <div class="description">
          <table class="table table-striped table-dark">
            <tbody>
              {% if j.status %}
                <tr>
                  <td>Status</td>
                  <td>{{j.status}}</td>
                </tr>
              {% endif %}
              {% if j.title %}
                <tr>
                  <td>Title</td>
                  <td>{{j.title}}</td>
                </tr>
              {% endif %}
              {% if j.company_name %}
                <tr>
                  <td>Company Name</td>
                  <td>{{j.company_name}}</td>
                </tr>
              {% endif %}
              {% if j.location %}
                <tr>
                  <td>Location</td>
                  <td>{{j.location}}</td>
                </tr>
              {% endif %}
              {% if j.about %}
                <tr>
                  <td>About</td>
                  <td>{{j.about}}</td>
                </tr>
              {% endif %}
              {% if j.qualifications %}
                <tr>
                  <td>Qualifications</td>
                  <td>{{j.qualifications}}</td>
                </tr>
              {% endif %}
              {% if j.responsibility %}
                <tr>
                  <td>Responsibility</td>
                  <td>{{j.responsibility}}</td>
                </tr>
              {% endif %}
              {% if j.experience %}
                <tr>
                  <td>Experience</td>
                  <td>{{j.experience}}</td>
                </tr>
              {% endif %}
              {% if j.job_type %}
                <tr>
                  <td>Job Type</td>
                  <td>{{j.job_type}}</td>
                </tr>
              {% endif %}
              {% if j.package %}
                <tr>
                  <td>Package</td>
                  <td>{{j.package}}</td>
                </tr>
              {% endif %}
              {% if j.skills %}
                <tr>
                  <td>Skills</td>
                  <td>{{j.skills}}</td>
                </tr>
              {% endif %}
            </tbody>
          </table>
        </div>
        </div>
      </div>
      <div class="empcard ">
        <div class="empcard-description">
          <h2 class="empcard-description-title">{{j.title}}</h2>
          <span class="empcard-description-subtitle">{{j.company_name}}</span>
          <span class="empcard-description-subtitle">{{j.location}}</span>
          <span class="empcard-description-skills">Status: {{s}}</span>
          <div style="display: flex; gap: 20px;">
            <button class="empcard-btn btn btn-light" onclick="viewEmp('mymodal{{forloop.counter0}}')">View More</button>
            {% if s == 'pending' %}
              <form action="" method="POST">
                {% csrf_token %}
                <button class="empcard-btn btn btn-danger" type="submit" value="{{j.id}}" name="submit">Withdraw</button>
              </form>
            {% endif %}
          </div>
        </div>
        <div class="emp-card-img">
          {% if j.logo %}
            <img class="empcard-image" src={{j.logo.url}}>
          {% else %}
            <img class="empcard-image" src="/media/empty-img.png">
          {% endif %}
        </div>
      </div>
    {% endfor %}
  </div>
</div>
{% endblock %}