admins/urls.py
from django.urls import path
from .views import (
  adminsLogin_view,
  adminsHome_view,
  adminsManageJob_view,
  adminsManageEmployee_view,
  adminsManageEmployer_view
)

app_name = 'admins'

urlpatterns = [
  path('login/', adminsLogin_view, name='adminsLogin_view'),
  path('home/', adminsHome_view, name='adminsHome_view'),
  path('manage-jobs/', adminsManageJob_view, name='adminsManageJob_view'),
  path('manage-employees/', adminsManageEmployee_view, name='adminsManageEmployee_view'),
  path('manage-employers/', adminsManageEmployer_view, name='adminsManageEmployer_view'),
]

eJobPortal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name="home-view"),
    path('logout/', logoutUser, name="logoutUser"),
    path('employee/', include('employee.urls', namespace='employee')),
    path('employer/', include('employer.urls', namespace='employer')),
    path('admins/', include('admins.urls', namespace='admins')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

employer/urls.py
from django.urls import path
from .views import (
  employerLogin_view,
  employerSignUp_view,
  employerHome_view,
  employerProfile_view,
  employerPostJob_view,
  employerJobStatus_view,
  employerApplicants_view,
  employerCreateThreads_view,
  employerListThreads_view,
  employerThreadView,
  employerCreateMessageView,
  employerPricing_view,
  checkOut,
  paymentSuccessful,
  paymentFailed
)

app_name = 'employer'

urlpatterns = [
  path('login/', employerLogin_view, name='employerLogin_view'),
  path('signup/', employerSignUp_view, name='employerSignUp_view'),
  path('home/', employerHome_view, name='employerHome_view'),
  path('profile/', employerProfile_view, name='employerProfile_view'),
  path('post-job/', employerPostJob_view, name='employerPostJob_view'),
  path('jobs-status/', employerJobStatus_view, name='employerJobStatus_view'),
  path('applicants/', employerApplicants_view, name='employerApplicants_view'),
  path('inbox/', employerListThreads_view, name='employerListThreads_view'),
  path('inbox/create-thread/', employerCreateThreads_view, name='employerCreateThreads_view'),
  path('inbox/<int:pk>/', employerThreadView, name='employerThreadView'),
  path('inbox/<int:pk>/create-message/', employerCreateMessageView, name='employerCreateMessageView'),
  path('pricing/', employerPricing_view, name='employerPricing_view'),
  path('checkout/<int:planid>/', checkOut, name='checkOut'),
  path('payment-success/', paymentSuccessful, name='paymentSuccessful'),
  path('payment-failed/', paymentFailed, name='paymentFailed'),
]

employer/models.py
from django.db import models
import jsonfield
from user.models import User
from django.contrib.auth.models import BaseUserManager
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.utils import timezone
from django.core.validators import FileExtensionValidator

class EmployerManager(BaseUserManager):
  def get_queryset(self, *args, **kwargs):
    results = super().get_queryset(*args, **kwargs)
    return results.filter(role=User.Role.EMPLOYER)

class EmployerRole(User):
  base_role = User.Role.EMPLOYER
  employer = EmployerManager()
  class Meta:
    proxy = True

@receiver(post_save, sender=EmployerRole)
def create_user_profile(sender, instance, created, **kwargs):
  if created and instance.role == "EMPLOYER":
    Employer.objects.create(user=instance)

class Employer(models.Model):
  id = models.BigAutoField(primary_key=True)
  user = models.OneToOneField(User, on_delete=models.CASCADE)
  photo = models.ImageField(default='avatar.png', upload_to='', blank=True)
  company_address = models.CharField(max_length=300, blank=True)
  company_name = models.CharField(max_length=300, blank=False, default='abc')
  phone_no = models.CharField(max_length=15, blank=False, default='12345')

jobType = [
  ('Full Time', 'Full Time'),
  ('Contract', 'Contract'),
  ('Internship', 'Internship')
]

class Job(models.Model):
  id = models.BigAutoField(primary_key=True)
  employer_id = models.ForeignKey(Employer, to_field='id', on_delete=models.CASCADE)
  title = models.CharField(max_length=150, null=False, blank=False)
  logo = models.ImageField(upload_to='', blank=True)
  company_name = models.CharField(max_length=300, null=False, blank=False)
  location = models.CharField(max_length=150, null=False, blank=False)
  about = models.CharField(max_length=3000, null=False, blank=False)
  qualifications = models.CharField(max_length=3000, blank=True)
  responsibility = models.CharField(max_length=3000, blank=True)
  experience = models.IntegerField(blank=True, null=True, default = 0)
  job_type = models.CharField(max_length=50, blank=True, choices=jobType)
  package = models.CharField(max_length=150, blank=True)
  skills = models.CharField(max_length=350, blank=True)
  status = models.CharField(max_length=50, default="pending", null=False, blank=False)

class Payments(models.Model):
  id = models.BigAutoField(primary_key=True)
  employer_id = models.ForeignKey(Employer, to_field='id', on_delete=models.CASCADE)
  date = models.DateTimeField(blank=False, null=False, default=timezone.now)
  amount = models.IntegerField(blank=False, null=False, default = 0)
  bill = models.FileField(upload_to='', blank=False, null=False, default = None, validators=[FileExtensionValidator(allowed_extensions=["pdf"])])

employer/forms.py
from django import forms
from .models import Employer, Job

class EmployerModelForm(forms.ModelForm):
  class Meta:
    model = Employer
    fields = (
      'photo',
      'phone_no',
      'company_address',
      'company_name'
    )

class JobModelForm(forms.ModelForm):
  class Meta:
    model = Job
    fields = '__all__'
    exclude = ('employer_id', 'status')

class MessageForm(forms.Form):
  message = forms.CharField(label='', max_length=3000)

employer/views.py
from django.shortcuts import render, redirect
from .models import EmployerRole, Employer, Job, Payments
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
from django.contrib import messages
from .forms import EmployerModelForm, JobModelForm, MessageForm
from employee.models import Employee, JobApplications
from itertools import chain
from user.models import ThreadModel, Messages, User
from django.db.models import Q
from instamojo_wrapper import Instamojo
from django.conf import settings
from django.core.files.base import ContentFile
from reportlab.pdfgen import canvas
from io import BytesIO
from datetime import datetime, timedelta, timezone
from django.urls import reverse
import urllib.parse

api = Instamojo(
  api_key = settings.API_KEY,
  auth_token = settings.AUTH_TOKEN,
  endpoint = 'https://test.instamojo.com/api/1.1/'
)

paymentResponse = None

def employerLogin_view(request):
  if request.user.is_authenticated:
    return render(request, 'emp-home.html')
  if request.method == 'POST':
    name = request.POST.get('name')
    password = request.POST.get('pass')
    user = authenticate(username=name, password=password)
    if user is not None and user.role == 'EMPLOYER':
      login(request, user)
      return redirect('employer:employerHome_view')
    else:
      messages.error(request,'Email or password is incorrect.')
      return redirect('employer:employerLogin_view')
  return render(request, 'emp-login.html')

def employerSignUp_view(request):
  if request.user.is_authenticated:
    return render(request, 'emp-home.html')
  if request.method == 'POST':
    ename = request.POST.get('name')
    email = request.POST.get('email')
    password = request.POST.get('pass')
    company = request.POST.get('company')
    phone = request.POST.get('phone')
    emp = EmployerRole.objects.create_user(username=ename, email=email, password=password)
    empObj = Employer.objects.filter(user=emp).first()
    empObj.company_name = company
    empObj.phone_no = phone
    empObj.save()
    return redirect('employer:employerLogin_view')
  return render(request, 'emp-signup.html')

@login_required
def employerHome_view(request):
  if request.user.role == 'EMPLOYER':
    emp = Employee.objects.all()
    form_data = {}
    if request.method == 'POST':
      d1 = Employee.objects.all()
      form_data = request.POST.dict()
      if (form_data['name']):
        d1 = d1.filter(user__username__icontains=form_data['name'])
      if form_data['experience']:
        d1 = d1.filter(experience=form_data['experience'])
      if form_data['skills']:
        d1 = d1.filter(skills__icontains=form_data['skills'])
      emp = d1
    context = {
      'emp': emp,
      'formData': form_data
    }
    return render(request, 'emp-home.html', context)

@login_required
def employerProfile_view(request):
  if request.user.role == 'EMPLOYER':
    employer = Employer.objects.filter(user=request.user).first()
    form = EmployerModelForm(request.POST or None, request.FILES or None, instance=employer)
    confirm = False
    confirmError = ''

    if request.method == 'POST':
      if form.is_valid():
        form.save()
        confirm = True
        confirmError = ''
      else:
        confirmError = form.errors
    
    context = {
      'employer': employer,
      'form': form,
      'confirm': confirm,
      'confirmError': confirmError
    }
    return render(request, 'emp-profile.html', context)

@login_required
def employerPostJob_view(request):
  if request.user.role == 'EMPLOYER':
    employer = Employer.objects.filter(user=request.user).first()
    form = JobModelForm(request.POST or None, request.FILES or None)
    confirm = False
    confirmError = ''
    payment = Payments.objects.filter(employer_id=employer.id)
    allowedPosts = 0
    today = datetime.now(timezone.utc)
    jobs = Job.objects.filter(employer_id=employer.id, status='approved')
    for p in payment:
      date = p.date + timedelta(days=30)
      date = date.replace(tzinfo=timezone.utc)
      if date >= today:
        if p.amount == 400:
          allowedPosts += 6 
        elif p.amount == 800:
          allowedPosts += 20

    if allowedPosts == 0:
      allowedPosts = 2

    if request.method == 'POST':
      if form.is_valid():
        f = form.save(commit=False)
        f.employer_id_id = employer.id
        f.save()
        form = JobModelForm()
        confirm = True
        confirmError = ''
      else:
        confirmError = form.errors
    
    context = {
      'form': form,
      'confirm': confirm,
      'confirmError': confirmError,
      'allowedPosts': allowedPosts,
      'jobs': jobs
    }
    return render(request, 'emp-postJob.html', context)

@login_required
def employerJobStatus_view(request):
  if request.user.role == 'EMPLOYER':
    emp = Employer.objects.filter(user=request.user).first()
    jobs = Job.objects.filter(employer_id=emp.id)
    confirm = False
    confirmError = ''

    if request.method == 'POST':
      form_data = request.POST.dict()
      if form_data['submit']:
        try:
          Job.objects.filter(id=form_data['submit']).delete()
          jobs = Job.objects.filter(employer_id=emp.id)
          confirm = True
          confirmError = ''
        except Exception as e:
          confirmError = e

    context = {
      'jobs': jobs,
      'confirm': confirm,
      'confirmError': confirmError
    }
    return render(request, 'emp-jobs-status.html', context)

@login_required
def employerApplicants_view(request):
  if request.user.role == 'EMPLOYER':
    confirm = False
    confirmError = ''
    if request.method == 'POST':
      try:
        form_data = request.POST.dict()
        if form_data['submit']:
          idList = form_data['submit'].split(',')
          instance = JobApplications.objects.filter(employee_id = idList[0], job_id = idList[1]).first()
          instance.status = idList[2]
          instance.save()
          confirm = True
          confirmError = ''
          if idList[2] == 'accepted':
            msgTo = Employee.objects.filter(id=idList[0]).first()
            url = '{}?{}'.format(reverse('employer:employerCreateThreads_view'), urllib.parse.urlencode({'messageTo': msgTo.user}))
            return redirect(url)
      except Exception as e:
        confirmError = e

    emp = Employer.objects.filter(user=request.user).first()
    jobs = Job.objects.filter(employer_id=emp.id, status='approved')
    ids = list(jobs.values_list('id', flat=True))
    resultList = []
    for j in jobs:
      obj = {'job': j}
      arr = []
      application = JobApplications.objects.filter(job_id=j.id, status='pending')
      applicationIds = list(application.values_list('employee_id', flat=True))
      for a in applicationIds:
        employee = Employee.objects.filter(id=a).first()
        arr.append(employee)
      obj['applicant'] = arr
      resultList.append(obj)

    context = {
      'jobApplicantList': resultList,
      'confirm': confirm,
      'confirmError': confirmError,
    }
    return render(request, 'emp-applicants.html', context)

@login_required
def employerListThreads_view(request):
  if request.user.role == 'EMPLOYER':
    threads = ThreadModel.objects.filter(Q(user=request.user) | Q(receiver=request.user))
    context = {
      'threads': threads
    }
    return render(request, 'emp-inbox.html', context)

@login_required
def employerCreateThreads_view(request):
  if request.user.role == 'EMPLOYER':
    form_data = {}
    if request.method == 'POST':
      form_data = request.POST.dict()
    if request.method == 'GET':
      form_data = request.GET.dict()
    if form_data['messageTo']:
      receiver = User.objects.get(username=form_data['messageTo'])
      if ThreadModel.objects.filter(user=request.user, receiver=receiver).exists():
        thread = ThreadModel.objects.filter(user=request.user, receiver=receiver).first()
        return redirect('employer:employerThreadView', pk=thread.pk)
      elif ThreadModel.objects.filter(user=receiver, receiver=request.user).exists():
        thread = ThreadModel.objects.filter(user=receiver, receiver=request.user).first()
        return redirect('employer:employerThreadView', pk=thread.pk)
      thread = ThreadModel(
        user=request.user,
        receiver=receiver
      )
      thread.save()
      return redirect('employer:employerThreadView', pk=thread.pk)

@login_required
def employerThreadView(request, pk):
  if request.user.role == 'EMPLOYER':
    form = MessageForm()
    thread = ThreadModel.objects.get(pk=pk)
    messageList = Messages.objects.filter(thread__pk__contains=pk)
    context = {
      'thread': thread,
      'form': form,
      'messageList': messageList
    }
    return render(request, 'emp-social-thread.html', context)

@login_required
def employerCreateMessageView(request, pk):
  if request.user.role == 'EMPLOYER':
    thread = ThreadModel.objects.get(pk=pk)
    if thread.receiver == request.user:
      receiver = thread.user
    else:
      receiver = thread.receiver

    message = Messages(
      thread=thread,
      from_id=request.user,
      to_id=receiver,
      description=request.POST.get('message')
    )
    message.save()
    return redirect('employer:employerThreadView', pk=pk)

@login_required
def employerPricing_view(request):
  return render(request, 'emp-pricing.html')

@login_required
def checkOut(request, planid):
  if request.user.role == 'EMPLOYER':
    host = request.get_host()
    plan = {
      'name': 'Free',
      'price': 0,
      'id': planid,
      'description': ['2 Active Posts']
    }
    price = 0
    if (planid == 1):
      price = 400
      plan['price'] = 400
      plan['name'] = 'Basic'
      plan['description'] = ['6 Active Posts']
    elif (planid == 2):
      price = 800
      plan['price'] = 800
      plan['name'] = 'Pro'
      plan['description'] = ['20 Active Posts']
    
    response = api.payment_request_create(
      amount = price,

employer/templates/emp-checkout.html
{% extends "base.html" %}

{% block content %}
<div class="page">
  <div class="page-box">
    <div class="checkoutcard">
      <h1>Purchase Details:</h1>
      <table class="table table-striped">
        <tbody>
          <tr>
            <td>Plan:</td>
            <td>{{plan.name}}</td>
          </tr>
          <tr>
            <td>Price:</td>
            <td>{{plan.price}}</td>
          </tr>
          <tr>
            <td>Description:</td>
            <td>
              {% for d in plan.description %}
                <p>{{d}}</p>
              {% endfor %}
            </td>
          </tr>
        </tbody>
      </table>
      <div style="display: flex;">
        <a href="{{payment_url}}" class="btn btn-info center">Pay Now</a>
      </div>
    </div>  
  </div>
</div>
{% endblock %}

employer/templates/emp-create-thread.html
{% extends "base.html" %}

{% block content %}
<div class="page">
  <div class="page-box">
    <div class="container">
      <div class="row">
        <div class="col-md-12 p-5">
          <a href="{% url 'employer:employerListThreads_view' %}" class="btn btn-light">Back to Your Inbox</a>
        </div>
      </div>
    
      <div class="row">
        <div class="col-md-12 p-5">
          <h3>Start a Conversation!</h3>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

employer/templates/emp-home.html
{% extends "base.html" %}

{% block content %}
<div class="page">
  <div class="page-box">
    <h3>Filters:</h3>
    <div>
      <form action="" method="POST" id="empFilterForm" class="ui form empFilter" enctype='multipart/form-data'>
        {% csrf_token %}
        <label for="name">Name:</label>
        <input type="text" placeholder="Eg - Akshita" name="name" id="name" value="{{formData.name}}">
        <label for="name">Experience:</label>
        <input type="number" placeholder="Eg - 3" name="experience" id="experience" value="{{formData.experience}}">
        <label for="name">Skills:</label>
        <input type="text" placeholder="Eg- Html, Css" name="skills" id="skills" value="{{formData.skills}}">
        <div class="actions">
          <button type='submit' class="btn btn-light">Apply</button>
        </div>
      </form>
    </div>
    {% if emp|length == 0 %}
      No employees available.
    {% endif %}
    {% for e in emp %}
      {% if e.availability != 'Closed to offers' %}
        <div class="ui modal mymodal mymodal{{forloop.counter0}}">
          <button style="float: right; margin: 10px;" onclick="hideEmp('mymodal{{forloop.counter0}}')"><i class="close icon" id="close-modal-btn"></i></button>
          <div class="header"></div>
          <div class="image content">
            <div class="ui medium image">
              <div class="prof-img">
                {% if e.photo %}
                  <img class="ui medium rounded image" src={{e.photo.url}}>
                {% else %}
                  <img class="ui medium rounded image" src="/media/avatar.png">
                {% endif %}
              </div>
            </div>
            <div class="description">
              <table class="table table-striped table-dark">
                <tbody>
                  <tr>
                    <td>Username</td>
                    <td>{{e.user}}</td>
                  </tr>
                  <tr>
                    <td>Email</td>
                    <td>{{e.user.email}}</td>
                  </tr>
                  <tr>
                    <td>Phone</td>
                    <td>{{e.phone_no}}</td>
                  </tr>
                  <tr>
                    <td>Resume</td>
                    <td>
                      {% if e.resume %}
                        <a href="{{e.resume.url}}" target="_blank">{{e.resume}}</a>
                      {% endif %}
                    </td>
                  </tr>
                  <tr>
                    <td>Address</td>
                    <td>{{e.location}}</td>
                  </tr>
                  <tr>
                    <td>Achievement</td>
                    <td>
                      <div class="profCardBox">
                        {% for a in e.achievement %}
                          <div class="profCard">
                            {% for value in a.values %}
                            <i class="chevron right icon"></i>{{ value }} 
                            {% endfor %}
                          </div>
                        {% endfor %}
                      </div>
                    </td>
                  </tr>
                  <tr>
                    <td>Primary Role</td>
                    <td>{{e.primary_role}}</td>
                  </tr>
                  <tr>
                    <td>Secondary Role</td>
                    <td>{{e.secondary_role}}</td>
                  </tr>
                  <tr>
                    <td>Experience</td>
                    <td>{{e.experience}}</td>
                  </tr>
                  <tr>
                    <td>Social Profiles</td>
                    <td>
                      <div class="profCardBox">
                        <div class="profCard">
                          Website: {{e.social_profiles.website}}
                        </div>
                        <div class="profCard">
                          Github: {{e.social_profiles.github}}
                        </div>
                        <div class="profCard">
                          LinkedIn: {{e.social_profiles.linkedIn}}
                        </div>
                        <div class="profCard">
                          Twitter: {{e.social_profiles.twitter}}
                        </div>
                      </div>
                    </td>
                  </tr>
                  <tr>
                    <td>Work Experience</td>
                    <td>
                      <div class="profCardBox">
                        {% for w in e.work_experience %}
                          <div class="profCard">
                            {% for value in w.values %}
                            <i class="chevron right icon"></i>{{ value }} &nbsp;
                            {% endfor %}
                          </div>
                        {% endfor %}
                      </div>
                    </td>
                  </tr>
                  <tr>
                    <td>Education</td>
                    <td>
                      <div class="profCardBox">
                        {% for e in e.education %}
                          <div class="profCard">
                            {% for value in e.values %}
                            <i class="chevron right icon"></i>{{ value }} &nbsp;
                            {% endfor %}
                          </div>
                        {% endfor %}
                      </div>
                    </td>
                  </tr>
                  <tr>
                    <td>Skills</td>
                    <td>{{e.skills}}</td>
                  </tr>
                  <tr>
                    <td>Availability</td>
                    <td>{{e.availability}}</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
        <div class="empcard ">
          <div class="empcard-description">
            <h2 class="empcard-description-title">{{e.user}}</h2>
            <span class="empcard-description-subtitle">{{e.user.email}}</span>
            <span class="empcard-description-subtitle">{{e.bio}}</span>
            {% if e.skills %}
              <span class="empcard-description-skills">Skills: {{e.skills}}</span>
            {% endif %}
            <div class="empcard-btn-box">
              <button class="empcard-btn btn btn-light" onclick="viewEmp('mymodal{{forloop.counter0}}')">View More</button>
              <form action="{% url 'employer:employerCreateThreads_view' %}" method="POST">
                {% csrf_token %}
                <button class="empcard-btn btn btn-info" type="submit" value="{{e.user}}" name="messageTo">Send Message</button>
              </form>
            </div>
          </div>
          <div class="emp-card-img">
            {% if e.photo %}
              <img class="empcard-image" src={{e.photo.url}}>
            {% else %}
              <img class="empcard-image" src="/media/avatar.png">
            {% endif %}
          </div>
        </div>
      {% endif %}
    {% endfor %}
  </div>
</div>
{% endblock %}

employer/templates/emp-inbox.html
{% extends "base.html" %}

{% block content %}
<div class="page">
  <div class="page-box">
    <div style="padding: 3rem 0 0 3rem!important;">
      <h2>Your Conversations -</h2>
    </div>
    {% for thread in threads.all %}
      <div class="row mb-3 p-5" style="border-bottom: 2px solid white;">
        <div class="card text-white bg-secondary mb-3 col-md-12 p-3 shadow-sm">
          <h4>{{ thread.user }} - {{ thread.receiver }}</h4>
          <a class="stretched-link" href="{% url 'employer:employerThreadView' thread.pk %}"></a>
        </div>
      </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

employer/templates/emp-login.html
{% extends "base.html" %}

{% block content %}
<div class="form-bg">
  <form class="ui form form-box" method="post">
    {% csrf_token %}
    <h2>Sign In</h2>
    <hr>
    <div class="field">
      <label>Username</label>
      <input type="text" name="name" placeholder="Eg - Akshita">
    </div>
    <div class="field">
      <label>Password</label>
      <input type="password" name="pass" placeholder="Eg - *********">
    </div>
    <button type="submit" class="btn btn-light">Sign In</button>
    <a href="{% url 'employer:employerSignUp_view' %}" >Not registered? Sign-up here</a>
    {% for message in messages %}
      <div class="alert alert-danger">
        <a class="close" href="#" data-dismiss="alert">×</a>
        {{ message }}
      </div>
    {% endfor %}
  </form>
</div>
{% endblock %}

employer/templates/emp-payment-failed.html
{% extends "base.html" %}

{% block content %}
<div class="page">
  <div class="page-box">
    <div class="payment-failed">
      <i class="exclamation circle icon payment-failed-icon"></i>
      <h1>Payment failed. Please try again later.</h1>
    </div>
  </div>
</div>
{% endblock %}

employer/templates/emp-payment-success.html
{% extends "base.html" %}

{% block content %}
<div class="page">
  <div class="page-box">
    <div class="payment-success">
      <i class="check circle outline icon payment-success-icon"></i>
      <h1>Payment completed successfully.</h1>
    </div>
  </div>
</div>
{% endblock %}

employer/templates/emp-postJob.html
{% extends "base.html" %}

{% block content %}
<div class="page">
  <div class="page-box">
    {% if confirm %}
      <div class="ui green message">Job Post created successfully. It will be posted after the approval.</div>
    {% elif confirmError != '' %}
      <div class="ui red message">{{confirmError}}</div>
    {% endif %}
    {% if jobs|length < allowedPosts %}
      <div class="job-post">
        <h2>Post a new Job</h2>
        <form action="" method="POST" class="ui form" enctype='multipart/form-data'>
          {% csrf_token %}
          {{form.as_p}}
          {{ form.employer_id.as_hidden }}
          <button type='submit' class="ui positive right labeled icon button">
            Post<i class="checkmark icon"></i>
          </button>
        </form>
      </div>
    {% else %}
      <div class="card text-white bg-secondary mb-3 p-5">
        <h2>You have reached your post limit.</h2>
        <h3><a style="color: white; text-decoration: underline;" href="{% url 'employer:employerPricing_view' %}">Purchase a plan to post more jobs</a></h3>
      </div>
    {% endif %}
  </div>
</div>
{% endblock %}

employer/templates/emp-pricing.html
{% extends "base.html" %}

{% block content %}
<div class="page">
  <div class="page-box">
    <h1 style="text-align: center; text-decoration: underline; margin-bottom: 2vw;">Pricing (per month)</h1>
    <div>
      <div class="empcard price-card">
        <div class="empcard-description">
          <h2 style="padding-bottom: 1vw; border-bottom: 1px solid black; font-weight: 600;">Free</h2>
          <h4><i class="arrow right icon"></i>2 Active Posts</h4>
        </div>
      </div>
      <div class="empcard price-card">
        <div class="empcard-description">
          <h2 style="padding-bottom: 1vw; border-bottom: 1px solid black; font-weight: 600;">
            Basic (<i class="rupee sign icon"></i>400 / month)
          </h2>
          <h4><i class="arrow right icon"></i>6 Active Posts</h4>
          <form action="{% url 'employer:checkOut' 1 %}" method="POST">
            {% csrf_token %}
            <button style="margin: 0 auto;" class="empcard-btn btn btn-light" type="submit" value="{{e.user}}" name="messageTo">Buy Now</button>
          </form>
        </div>
      </div>
      <div class="empcard price-card">
        <div class="empcard-description">
          <h2 style="padding-bottom: 1vw; border-bottom: 1px solid black; font-weight: 600;">
            Pro (<i class="rupee sign icon"></i>800 / month)
          </h2>
          <h4><i class="arrow right icon"></i>20 Active Posts</h4>
          <form action="{% url 'employer:checkOut' 2 %}" method="POST">
            {% csrf_token %}
            <button style="margin: 0 auto;" class="empcard-btn btn btn-light" type="submit" value="{{e.user}}" name="messageTo">Buy Now</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

employer/templates/emp-social-thread.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="page">
  <div class="page-box">
    <div class="container">
      <div class="row">
        <div class="card text-white bg-secondary mb-3 col-md-12 mt-5 p-3 shadow-sm">
          {% if thread.receiver == request.user %}
            <h4>@{{ thread.user }}</h4>
          {% else %}
            <h4>@{{ thread.receiver }}</h4>
          {% endif %}
        </div>
      </div>
      {% if messageList.all.count == 0 %}
      <div class="row my-5">
        <div class="col-md-12">
          <p class="empty-text">No Messages</p>
        </div>
      </div>
      {% endif %}
      {% for message in messageList %}
      <div class="row">
        <div class="col-md-12 my-1">
          {% if message.from_id == request.user %}
            <div class="sent-message my-3">
              <p>{{ message.description }}</p>
            </div>
          {% elif message.to_id == request.user %}
            <div class="received-message my-3">
              <p>{{ message.description }}</p>
            </div>
          {% endif %}
        </div>
      </div>
      {% endfor %}
      <div class="row">
        <div class="card text-white bg-secondary mb-3 col-md-12 p-3 shadow-sm">
          <form method="POST" action="{% url 'employer:employerCreateMessageView' thread.pk %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form | crispy }}
            <div style="display: flex;">
              <button class="btn btn-info center" type="submit">Send Message</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}