admins/urls.py
from django.urls import path
from .views import (
  adminsLogin_view,
  adminsHome_view,
  adminsManageJob_view,
  adminsManageEmployee_view,
  adminsManageEmployer_view
)

app_name = 'admins'

urlpatterns = [
  path('login/', adminsLogin_view, name='adminsLogin_view'),
  path('home/', adminsHome_view, name='adminsHome_view'),
  path('manage-jobs/', adminsManageJob_view, name='adminsManageJob_view'),
  path('manage-employees/', adminsManageEmployee_view, name='adminsManageEmployee_view'),
  path('manage-employers/', adminsManageEmployer_view, name='adminsManageEmployer_view'),
]

eJobPortal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name="home-view"),
    path('logout/', logoutUser, name="logoutUser"),
    path('employee/', include('employee.urls', namespace='employee')),
    path('employer/', include('employer.urls', namespace='employer')),
    path('admins/', include('admins.urls', namespace='admins')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

employee/urls.py
from django.urls import path
from .views import (
  employeeLogin_view,
  employeeSignUp_view,
  employeeHome_view,
  employeeProfile_view,
  employeeTrackApplication_view,
  employeeListThreads_view,
  employeeThreadView,
  employeeCreateMessageView
)

app_name = 'employee'

urlpatterns = [
  path('login/', employeeLogin_view, name='employeeLogin_view'),
  path('signup/', employeeSignUp_view, name='employeeSignUp_view'),
  path('home/', employeeHome_view, name='employeeHome_view'),
  path('profile/', employeeProfile_view, name='employeeProfile_view'),
  path('track-applications/', employeeTrackApplication_view, name='employeeTrackApplication_view'),
  path('inbox/', employeeListThreads_view, name='employeeListThreads_view'),
  path('inbox/<int:pk>/', employeeThreadView, name='employeeThreadView'),
  path('inbox/<int:pk>/create-message/', employeeCreateMessageView, name='employeeCreateMessageView'),
]

employer/urls.py
from django.urls import path
from .views import (
  employerLogin_view,
  employerSignUp_view,
  employerHome_view,
  employerProfile_view,
  employerPostJob_view,
  employerJobStatus_view,
  employerApplicants_view,
  employerCreateThreads_view,
  employerListThreads_view,
  employerThreadView,
  employerCreateMessageView,
  employerPricing_view,
  checkOut,
  paymentSuccessful,
  paymentFailed
)

app_name = 'employer'

urlpatterns = [
  path('login/', employerLogin_view, name='employerLogin_view'),
  path('signup/', employerSignUp_view, name='employerSignUp_view'),
  path('home/', employerHome_view, name='employerHome_view'),
  path('profile/', employerProfile_view, name='employerProfile_view'),
  path('post-job/', employerPostJob_view, name='employerPostJob_view'),
  path('jobs-status/', employerJobStatus_view, name='employerJobStatus_view'),
  path('applicants/', employerApplicants_view, name='employerApplicants_view'),
  path('inbox/', employerListThreads_view, name='employerListThreads_view'),
  path('inbox/create-thread/', employerCreateThreads_view, name='employerCreateThreads_view'),
  path('inbox/<int:pk>/', employerThreadView, name='employerThreadView'),
  path('inbox/<int:pk>/create-message/', employerCreateMessageView, name='employerCreateMessageView'),
  path('pricing/', employerPricing_view, name='employerPricing_view'),
  path('checkout/<int:planid>/', checkOut, name='checkOut'),
  path('payment-success/', paymentSuccessful, name='paymentSuccessful'),
  path('payment-failed/', paymentFailed, name='paymentFailed'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script type="text/javascript" src={% static 'main.js' %}></script>
    <link rel="stylesheet" type="text/css" href={% static 'style.css' %}>
    <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    <title>e-Job Portal - {% block title %}{% endblock title %}</title>
  </head>
  <body>
    {% url 'home-view' as path_to_home %}
    {% if request.user.is_authenticated %}
      {% if request.user.role == 'EMPLOYEE' %}
        {% url 'employee:employeeHome_view' as path_to_home %}
      {% endif %}
    {% endif %}
    {% if request.user.is_authenticated %}
      {% if request.user.role == 'EMPLOYER' %}
        {% url 'employer:employerHome_view' as path_to_home %}
      {% endif %}
    {% endif %}
    <nav class="navbar e-nav">
      <div class="ui container">
        <a href="{{path_to_home}}" class="{% if request.path == path_to_home %}active{% endif %} item">
          <h3>e-Job Portal</h3>
        </a>
        <div class="right menu">
          {% if request.user.is_authenticated %}
          <a href="{% url 'logoutUser' %}" class="ui item">
            Logout
          </a>
          {% else %}
          <a href="{% url 'employee:employeeSignUp_view' %}" class="ui item">
            Join as employee /
          </a>
          <a href="{% url 'employer:employerSignUp_view' %}" class="ui item">
            Join as employer
          </a>
          {% endif %}
        </div>
      </div>
    </nav>
    {% if request.user.is_authenticated %}
    <div class="ui demo vertical inverted sidebar labeled icon menu">
      {% if request.user.role == 'EMPLOYEE' %}
        <a class="item" href="{% url 'employee:employeeHome_view' %}">
          <i class="home icon"></i>Home
        </a>
        <a class="item" href="{% url 'employee:employeeProfile_view' %}">
          <i class="user icon"></i>Profile
        </a>
        <a class="item" href="{% url 'employee:employeeTrackApplication_view' %}">
          <i class="location arrow icon"></i>Track<br>Applications
        </a>
        <a class="item" href="{% url 'employee:employeeListThreads_view' %}">
          <i class="comments icon"></i>Inbox
        </a>
      {% elif request.user.role == 'EMPLOYER' %}
        <a class="item" href="{% url 'employer:employerHome_view' %}">
          <i class="home icon"></i>Home
        </a>
        <a class="item" href="{% url 'employer:employerProfile_view' %}">
          <i class="user icon"></i>Profile
        </a>
        <a class="item" href="{% url 'employer:employerPostJob_view' %}">
          <i class="edit icon"></i>Post Job
        </a>
        <a class="item" href="{% url 'employer:employerJobStatus_view' %}">
          <i class="location arrow icon"></i>Jobs Status
        </a>
        <a class="item" href="{% url 'employer:employerApplicants_view' %}">
          <i class="male icon"></i>Applicants
        </a>
        <a class="item" href="{% url 'employer:employerListThreads_view' %}">
          <i class="comments icon"></i>Inbox
        </a>
        <a class="item" href="{% url 'employer:employerPricing_view' %}">
          <i class="rupee sign icon"></i>Pricing
        </a>
      {% elif request.user.role == 'ADMIN' %}
        <a class="item" href="{% url 'admins:adminsHome_view' %}">
          <i class="home icon"></i>Home
        </a>
        <a class="item" href="{% url 'admins:adminsManageJob_view' %}">
          <i class="edit icon"></i>Manage<br>Jobs
        </a>
        <a class="item" href="{% url 'admins:adminsManageEmployee_view' %}">
          <i class="male icon"></i>Manage<br>Employees
        </a>
        <a class="item" href="{% url 'admins:adminsManageEmployer_view' %}">
          <i class="user icon"></i>Manage<br>Employers
        </a>
      {% endif %}
    </div>
    {% endif %}
    <div class="main-box">
      {% block content %}
      {% endblock content %}
    </div>
    {% block scripts %}
    {% endblock scripts %}
  </body>
</html>

templates/index.html
{% extends "base.html" %}

{% block head_title %}{% endblock %}

{% block content %}
  <div class="home-box">
    <h1>e-Job Portal</h1>
    <div class="home-content">
      <div class="quote">
        <h2>Join The Best</h2>
        <h2>Be The Best</h2>
      </div>
      <br><hr>
      <div class="home-btn">
        <a href="{% url 'employee:employeeLogin_view' %}">
          <button class="ui secondary button" onclick="redirectEmployeeLogin()">
            Find your next Job
          </button>
        </a>
        <span></span>
        <a href="{% url 'employer:employerLogin_view' %}">
          <button class="ui secondary button" onclick="redirectEmployerLogin()">
            Find your next Hire
          </button>
        </a>
      </div>
    </div>
  </div>
{% endblock %}